### ISSUE TITLE
ontofetch.py cannot handle owl files with includes

### ISSUE THREAD

**Issue by ivansg44** [GenEpiO/geem#23]
![image](https://user-images.githubusercontent.com/34198261/44937831-26746d80-ad30-11e8-871b-7436e050815c.png)

Command line arguments:

`$ python ontofetch.py http://purl.obolibrary.org/obo/foodon.owl -o fetched_ontologies/`

**Comment by Public-Health-Bioinformatics** [comment]
This is now fixed. A conditional had wrong indentation level.
