### ISSUE TITLE
contrib.auth.views.login(), logout() deprecated

### ISSUE THREAD

**Issue by ivansg44** [GenEpiO/geem#29]
[contrib.auth.views.login(), logout() were deprecated in Django 2.1.](https://docs.djangoproject.com/en/2.1/releases/2.1/#features-removed-in-2-1)

As a result, I ran into issues when creating a development server. Here are the changes I made locally to correct the issue, at [lines 33-34 of geem/urls.py](https://github.com/GenEpiO/geem/blob/52d942d18e11c7915f828ea99d35be2973543807/geem/urls.py#L33):

```diff
@@ -30,6 +30,6 @@ urlpatterns = [
     #path('data/private/', views.private_packages),
     #path('data/private/<file_name>/', views.private_package),
 
-    path('accounts/login', auth_views.login, name='login', kwargs={'template_name': 'geem/login.html'}),
-    path('accounts/logout', auth_views.logout, name='logout', kwargs={'next_page': reverse_lazy('portal')}),
+    path('accounts/login', auth_views.LoginView.as_view(template_name='geem/login.html'), name='login'),
+    path('accounts/logout', auth_views.LogoutView.as_view(next_page=reverse_lazy('portal')), name='logout'),
 ]
```

This allowed me to set up the development server using Docker.

**Comment by ddooley** [comment]
Good stuff. I've implemented in my branch; and closed.
