### ISSUE TITLE
``ontofetch.py`` not returning all contents under specified root

### ISSUE THREAD

**Issue by ivansg44** [GenEpiO/geem#37]
Try running ``ontofetch.py`` with the following arguments:

``http://purl.obolibrary.org/obo/foodon.owl -r http://purl.obolibrary.org/obo/BFO_0000001``

Observe ["food material"](https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_00002403), and some of its children (e.g., [seafood product](https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_00001046)), were not fetched in the resulting output.

Now try:

``http://purl.obolibrary.org/obo/foodon.owl -r http://purl.obolibrary.org/obo/FOODON_00002403``.

Observe [seafood product](https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_00001046) was now fetched, but other children (e.g., [baked beans (dish)](https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_03301946) were not.

**Comment by ddooley** [comment]
Moved to ontofetch repository: https://github.com/Public-Health-Bioinformatics/ontofetch/issues/1
